% Auto-generated by cameraCalibrator app on 12-Oct-2025
%-------------------------------------------------------

% Auto-generated by cameraCalibrator app on 18-Oct-2025
%-------------------------------------------------------


% Define images to process
imageFileNames = {'...path\matlab\final\calibration hres\ex_images_hres\imgLaser_1.jpg',...
    '...path\matlab\final\calibration hres\ex_images_hres\imgLaser_2.jpg',...
    '...path\matlab\final\calibration hres\ex_images_hres\imgLaser_3.jpg',...
    '...path\matlab\final\calibration hres\ex_images_hres\imgLaser_4.jpg',...
    '...path\matlab\final\calibration hres\ex_images_hres\imgLaser_5.jpg',...
    '...path\matlab\final\calibration hres\ex_images_hres\imgLaser_6.jpg',...
    '...path\matlab\final\calibration hres\ex_images_hres\imgLaser_7.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
minCornerMetric = 0.150000;
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames, 'MinCornerMetric', minCornerMetric);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25.000000;  % in millimeters
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParamsLaserhres, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParamsLaserhres);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParamsLaserhres, 'CameraCentric');

% Display parameter estimation errors
%displayErrors(estimationErrors, cameraParamsLaserhres);

% For example, you can use the calibration data to remove effects of lens distortion.
%undistortedImage = undistortImage(originalImage, cameraParamsLaserhres);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
