% Auto-generated by cameraCalibrator app on 12-Oct-2025
%-------------------------------------------------------

% Define images to process
imageFileNames = {'C:...pathS\matlab\final\calibration hres\cal_images_hres\checker8x6_25mm_1.jpg',...
    '...path\matlab\final\calibration hres\cal_images_hres\checker8x6_25mm_2.jpg',...
    '...path\matlab\final\calibration hres\cal_images_hres\checker8x6_25mm_3.jpg',...
    '...path\matlab\final\calibration hres\cal_images_hres\checker8x6_25mm_4.jpg',...
    % ...
    '...path\matlab\final\calibration hres\cal_images_hres\checker8x6_25mm_29.jpg',...
    '...path\matlab\final\calibration hres\cal_images_hres\checker8x6_25mm_30.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
minCornerMetric = 0.150000;
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames, 'MinCornerMetric', minCornerMetric);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25.000000;  % in millimeters
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParamsInhres, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParamsInhres);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParamsInhres, 'CameraCentric');

% Display parameter estimation errors
%displayErrors(estimationErrors, cameraParamsInhres);

% For example, you can use the calibration data to remove effects of lens distortion.
%undistortedImage = undistortImage(originalImage, cameraParamsInhres);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
